camel:
  springboot:
    # The Camel context name
    name: CamelRestSql
#  component:
#    servlet:
#      mapping:
#        enabled: true
#        context-path: /product-service/*

# Binding health checks to a different port
management:
  port: 8081

# disable all management enpoints except health
endpoints:
  enabled: false
  health:
    enabled: true
  shutdown:
    sensitive: false
    enabled: true

spring:
  # Spring JDBC configuration
  datasource:
    url:      jdbc:mysql://192.100.30.100:3306/test
    username: fuse
    password: fuse

# The application configuration properties
quickstart:
  generateOrderPeriod: 2s
  processOrderPeriod: 5s
