apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: mysql
  name: mysql
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    app: mysql
    deploymentconfig: mysql
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      post:
        execNewPod:
          command:
          - /bin/sh
          - -c
          - |-
            hostname && sleep 10 && /opt/rh/rh-mysql56/root/usr/bin/mysql -h $MYSQL_SERVICE_HOST -u $MYSQL_USER -D $MYSQL_DATABASE -p$MYSQL_PASSWORD -P 3306 -e 'CREATE TABLE orders(
             id INTEGER AUTO_INCREMENT,
             product TEXT,
             vendor TEXT,
             quantity INT,
             orderdate  DATETIME,
             PRIMARY KEY (id)
             ) COMMENT="Orders test tables";

             INSERT INTO orders ( product, vendor, quantity, orderdate) VALUES ("Sphere", "Volume inc", 1, "2014-11-10");
             INSERT INTO orders ( product, vendor, quantity, orderdate) VALUES ("Cube", "Volume inc", 1, "2015-2-18");
             INSERT INTO orders ( product, vendor, quantity, orderdate) VALUES ("Cylinder", "Volume inc", 1, "2015-3-20");
             INSERT INTO orders ( product, vendor, quantity, orderdate) VALUES ("Circle", "Planar ltd", 1, "2011-3-4");
             INSERT INTO orders ( product, vendor, quantity, orderdate) VALUES ("Square", "Planar ltd", 1, "2014-5-5");
             INSERT INTO orders ( product, vendor, quantity, orderdate) VALUES ("Rectangle", "Planar ltd", 1, "2017-1-6");' && sleep 60
          containerName: mysql
        failurePolicy: ignore
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      creationTimestamp: null
      labels:
        app: mysql
        deploymentconfig: mysql
    spec:
      containers:
      - env:
        - name: MYSQL_DATABASE
          value: integrationdb
        - name: MYSQL_PASSWORD
          value: mysql
        - name: MYSQL_USER
          value: mysql
        image: registry.access.redhat.com/rhscl/mysql-56-rhel7
        imagePullPolicy: Always
        name: mysql
        ports:
        - containerPort: 3306
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/mysql/data
          name: mysql-volume-1
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: mysql-volume-1
  test: false
status:
  availableReplicas: 1
  details:
    causes:
    - type: Manual
    message: manual change
  latestVersion: 2
  observedGeneration: 4
  readyReplicas: 1
  replicas: 1
  unavailableReplicas: 0
  updatedReplicas: 0
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    template: mysql-ephemeral
spec:
  ports:
    - name: mysql
      protocol: TCP
      port: 3306
      targetPort: 3306
      nodePort: 0
  selector:
    app: mysql
    deploymentconfig: mysql
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
